tester/tester/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^test/', include('testing.urls', namespace='testing', app_name='testing')),
]

tester/testing/urls.py
from django.conf.urls import url
from .views import IndexView, RedirectToQuestions, QuestionDetail

app_name = 'tester'
urlpatterns=[
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', RedirectToQuestions.as_view(), name='redirect_to_questions'),
    url(r'^(?P<test_pk>[0-9]+)/(?P<question_num>[0-9]+)/$', QuestionDetail.as_view(), name='question'),

    url(r'^vote$', QuestionDetail.as_view(), name='vote'),
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
]

tester/testing/models.py
from django.db import models


class Test(models.Model):
    title = models.CharField('заголовок теста', max_length=100, unique=True)
    creation_date = models.DateField('дата создания', auto_now=True)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'тест'
        verbose_name_plural = 'тесты'
        ordering = ['title']


class Question(models.Model):
    test = models.ForeignKey(Test)
    text = models.TextField('текст вопроса', max_length=1000)
    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'вопрос'
        verbose_name_plural = 'вопросы'


class QuestionSimple(Question):
    pass



class Answer(models.Model):
    question = models.ForeignKey(Question)
    text = models.TextField('текст ответа', max_length=200)
    correct = models.BooleanField('правильный?', default=False)
    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'ответ'
        verbose_name_plural = 'ответы'

tester/testing/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse,Http404
from django.views import View
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import RedirectView
from django.views.generic import TemplateView

from .models import Test,Question, Answer
from django.template import RequestContext,loader


class IndexView(ListView):
    template_name = 'testing/index.html'
    context_object_name = 'tests'

    def get_queryset(self):
        return Test.objects.order_by('-creation_date')[:5]

class RedirectToQuestions(RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        return reverse('testing:question', kwargs={'test_pk': kwargs['pk'], 'question_num': 1})


class QuestionDetail(TemplateView):
    template_name = 'testing/detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        n = int(kwargs['question_num']) - 1
        context['question'] = Question.objects.filter(test=kwargs['test_pk']).all()[n:n+1][0]
        print(context['question'])
        q_pk = context['question'].pk
        context['answers'] = Answer.objects.filter(question=q_pk).all()

        if n + 1 == Question.objects.filter(test=kwargs['test_pk']).count():
            context['next_number'] = None
        else:
            context['next_number'] = n + 2
        context["test_pk"] = kwargs['test_pk']
        return context

    def post(self, request):
        print(request.POST['answer'])
        return HttpResponse("You're are voting on question.")

# def test(request, title_id):
#     question = get_object_or_404(Question, pk=title_id)
#     return render(request, 'testing/detail.html', {'question': question})


def vote(request):
    return HttpResponse("You're are voting on question.")


#
# def index(request):
#     latest_question_list = Test.objects.order_by('-creation_date')[:5]
#     template=loader.get_template('testing/index.html')
#     context=RequestContext(request,{'latest_question_list':latest_question_list,})
#     # output = ', '.join([q.title for q in latest_question_list])
#     return HttpResponse(template.render(context))
#     # html = "<H1>Index !!!</H1><HR>"
    # return HttpResponse(html)

tester/templates/testing/detail.html
<!DOCTYPE html>
<h1>({{question.id}}) {{ question.text }}</h1>

<ul>
{% for answer in answers %}
    <li>{{answer.text }}</li>

{% endfor %}
</ul>

<form action="{% url 'testing:vote' %}" method="post">
    {% csrf_token %}
    {%for answer in answers %}
        <input type="radio" name="answer" id="answer{{forloop.counter}}" value="{{answer.id}}" />
        <label for="answer{{forloop.counter}}">{{answer.text}}</label><br />
    {% endfor %}
    <input type="submit" value="Send">
</form>


<form action="{% url 'testing:vote' %}" method="post">
    {% csrf_token %}
    <input type="text" name="value" value="1234">
    <input type="submit" value="Send">
</form>

{% if next_number %}
    <a href="{% url 'testing:question' test_pk=test_pk question_num=next_number %}">Next</a>
{% endif %}

tester/templates/testing/index.html
<ul>Тесты</ul>
{% block title %}Тестирование{% endblock title %}

{% if tests %}
    <ul>
    {% for t in tests %}
        <li><a href="{% url 'testing:redirect_to_questions' pk=t.id %}">{{ t.title }}</a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}